name: Download Automático

on:
  schedule:
    # A tarefa será executada todos os dias às 10:30 (horário UTC)
    # Ajuste o horário para o seu fuso. O horário de Brasília (UTC-03)
    # precisa ser convertido para UTC. Ex: 10:30 BRT = 13:30 UTC.
    - cron: '30 13 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python download_script.py
